# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 24 May 2017 20:22:06 +0000
*               @ALL          0
*               @user         8
